#!/bin/bash

# Check if our environment is set up or not
if [ -z "$LLVM_HARNESS_HOME_DIR" ]; then
    echo "Error: The llvm-harness environment has not been brought up."
    exit 1
fi

XCLI_NAME="claudecode"
MODEL_NAME="claude-opus-4-6"
RESULTS_DIR=""
CLEAN_FLAG=0
RESET_FLAG=0

usage() {
    echo "Usage: $0 [-x xcli_name] [-m model_name] [--clean] [--reset] -s <results_dir>"
    echo "  -s, --results-dir     Directory of the results generated by autofix (required)"
    echo "  -x, --xcli            Name of the xcli to use (default: claudecode)"
    echo "  -m, --model           Name of the model to use (default: claude-opus-4-6)"
    echo "  -R, --reset           Reset the autoreview results before running (default: false)"
    echo "  -C, --clean           Clean build directories after running each issue (default: false)"
    echo "  -h, --help            Show this help message and exit"
    exit 1
}

while [[ $# -gt 0 ]]; do
    case "$1" in
        -x|--xcli)
            [[ -n "$2" ]] || { echo "Error: --xcli requires a value."; usage; }
            XCLI_NAME="$2"
            shift 2
            ;;
        -m|--model)
            [[ -n "$2" ]] || { echo "Error: --model requires a value."; usage; }
            MODEL_NAME="$2"
            shift 2
            ;;
        -s|--results-dir)
            [[ -n "$2" ]] || { echo "Error: --results-dir requires a value."; usage; }
            RESULTS_DIR="$2"
            shift 2
            ;;
        -C|--clean)
            CLEAN_FLAG=1
            shift
            ;;
        -R|--reset)
            RESET_FLAG=1
            shift
            ;;
        -h|--help)
            usage
            ;;
        *)
            echo "Error: Unknown option: $1"
            usage
            ;;
    esac
done

if [ -z "$RESULTS_DIR" ]; then
    echo "Error: -s|--results-dir is required."
    usage
fi

if [ ! -d "$RESULTS_DIR" ]; then
    echo "Error: The results directory $RESULTS_DIR does not exist."
    exit 1
elif [ ! -d "$RESULTS_DIR"/success ]; then
    echo "Error: The success directory $RESULTS_DIR/success does not exist."
    exit 1
fi

# We run everything from the home directory
USER_WORKING_DIR=$(pwd)
cd "$LLVM_HARNESS_HOME_DIR"

REVIEW_RESULTS_DIR=$RESULTS_DIR/autoreview
PROCESSED_ISSUES_FILE=$REVIEW_RESULTS_DIR/processed_issues

echo "Starting reviewing ..."
echo "==============================================="
echo "  X-CLI: $XCLI_NAME"
echo "  Model: $MODEL_NAME"
echo "  Clean: $CLEAN_FLAG"
echo "  Reset: $RESET_FLAG"
echo "  Reviewing: $RESULTS_DIR"
echo "  Review results: $REVIEW_RESULTS_DIR"
echo "  Processed issues file: $PROCESSED_ISSUES_FILE"
echo "==============================================="

echo
echo "Please double-check the above information."
read -p "Do you want to proceed? (y/n) " -r REPLY
echo
if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    echo "Benchmark aborted by user."
    exit 0
fi

if [ $RESET_FLAG -eq 1 ]; then
    echo "Resetting autoreview results in $REVIEW_RESULTS_DIR ..."
    rm -rf "$REVIEW_RESULTS_DIR"
fi

mkdir -p "$REVIEW_RESULTS_DIR"
touch "$PROCESSED_ISSUES_FILE"

for stats_path in "$RESULTS_DIR"/success/*.json; do
    if [[ "$stats_path" == *.summary.json ]]; then
        continue
    fi

    timestamp=$(date +"%m%d%H%M")

    echo "Extracting information from stats file: $stats_path"
    issue_id=$(jq -r '.command.issue' "$stats_path")
    if [ -z "$issue_id" ]; then
        echo "Error: Failed to extract issue id from $stats_path"
        continue
    fi

    # If this issue has been processed, skip it
    if grep -q "$issue_id" "$PROCESSED_ISSUES_FILE"; then
        echo "Issue $issue_id has already been processed. Skipping."
        echo
        continue
    fi

    patch_diff=$(jq -r '.patch' "$stats_path")
    patch_file=/tmp/${issue_id}_${timestamp}.patch
    echo "$patch_diff" > "$patch_file"

    echo "Issue: $issue_id"
    echo "Patch: $patch_file (${patch_diff:0:80}...)"

    report_file=$REVIEW_RESULTS_DIR/${issue_id}_review_${timestamp}.md
    temp_log=$REVIEW_RESULTS_DIR/${issue_id}_review_${timestamp}.log

    echo "Reviewing patch ..."
    if python -m autoreview.xcli --xcli "$XCLI_NAME" --model "$MODEL_NAME" --issue "$issue_id" --patch "$patch_file" --output "$report_file" > "$temp_log" 2>&1; then
        echo "Review completed successfully. Log saved to $temp_log"
    else
        echo "Error: Review for issue $issue_id failed. Check log at $temp_log for details."
    fi

    echo "$issue_id" >> "$PROCESSED_ISSUES_FILE"

    rm -rf "$patch_file" >/dev/null 2>&1
    if [ $CLEAN_FLAG -eq 1 ]; then
        rm -rf "$LAB_LLVM_BUILD_DIR/$issue_id" >/dev/null 2>&1
    fi
    rm -rf "$LLVM_HARNESS_HOME_DIR"/core.* >/dev/null 2>&1

    echo "Sleeping for 5 minutes before reviewing next patch ..."
    sleep 5m

    echo # Continue to the next one
done
